Useing Obsidian Callouts for Highlights and Annotations.
OGKevin/obsidian-kobo-highlights-import pull request #56
Opened 2022-12-11 05:54 UTC by android272

I changed the code to add the ability to turn on and off Obsidian callouts for highlights and annotations. Not only that but I also gave users the ability to change which callout to use for each highlights and annotations. You can turn this off to go back to the normal markdown block quotes.

2022-12-11 10:42 UTC, OGKevin requested changes
Thanks for this PR!

Do you mind adding a few test cases like the following: https://github.com/OGKevin/obsidian-kobo-highlights-import/blob/e1f46a30d73322f27f01b78a50385046855cb955/src/database/Highlight.test.ts#L34-L60

I know you can't run the test, as they are run with my Database, but if you could just write the test cases would be great. I can then run the test and make the adjustments needed to make it pass, if some fail.

2022-12-11 10:42 UTC, OGKevin commented on README.md
> +You can turn off callouts to go back to normal markdown block quotes as well as change which callout to use for highlights and annotations.
Could you please link to the following doc: https://help.obsidian.md/How+to/Use+callouts

2022-12-11 10:42 UTC, OGKevin commented on src/settings/Settings.ts
> +            .setDesc(`If the exported higlights should use callouts ex: '> [!quote]' & '> [!note]'`)
Is it possible to link to the docs here as well? https://help.obsidian.md/How+to/Use+callouts

2022-12-17 09:55 UTC, OGKevin commented
Alright, @android272 if you could merge: https://github.com/android272/obsidian-kobo-highlights-import/pull/1 then this one can be merged as well 👍🏾

2022-12-18 21:03 UTC, android272 commented
Yeah, I just have a few more edits to do before I merge.

2023-01-03 03:18 UTC, android272 commented
Is there anything that you need me to do for this?

2023-01-03 18:08 UTC, OGKevin commented
Hey Andrew, I’ve been on a long vacation without 💻. I’ll be back next week and will have a look then! On 3 Jan 2023, at 04:19, Andrew Pullins ***@***.***> wrote:﻿
Is there anything that you need me to do for this?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2023-01-11 16:23 UTC, merged